type PdfJsRuntime = typeof import('pdfjs-dist/build/pdf.mjs');

let runtimePromise: Promise<PdfJsRuntime> | undefined;

const loadBrowserRuntime = async (): Promise<PdfJsRuntime> => {
  const [pdfjs, workerAsset] = await Promise.all([
    import('pdfjs-dist/build/pdf.mjs'),
    import('pdfjs-dist/build/pdf.worker.min.mjs?url')
  ]);

  // Vite owns the worker URL so its hash and base path always match the build.
  // Do not use pdfjs-dist/webpack.mjs here: it eagerly constructs a worker at
  // module evaluation time and bypasses PDF.js' normal worker error handling.
  pdfjs.GlobalWorkerOptions.workerPort = null;
  pdfjs.GlobalWorkerOptions.workerSrc = workerAsset.default;

  if (!pdfjs.GlobalWorkerOptions.workerSrc) {
    throw new Error('PDF.js worker URL was not generated by the application build.');
  }

  return pdfjs;
};

export const loadPdfJsRuntime = (): Promise<PdfJsRuntime> => {
  runtimePromise ||= typeof window === 'undefined'
    ? import('pdfjs-dist/legacy/build/pdf.mjs') as Promise<PdfJsRuntime>
    : loadBrowserRuntime();
  return runtimePromise;
};

export const resetPdfJsRuntimeForTests = () => {
  runtimePromise = undefined;
};
